Repository sharesight/www.sharesight.com, pull requests merged in 2021-03, with the labels that each got.

#242 Update pricing page from 150k users to 200k users
  source/page-pricing.html.erb
Labels: On STAGING

#244 Add Github Actions to dependabot.
  .github/dependabot.yml
Labels: dependencies

#245 Specify [latest] versions for `checkout` and `slatify` actions.
  .github/workflows/bundle-audit.yml
  .github/workflows/main.yml
Labels: On STAGING, dependencies

#251 Convert some links to https.
  data/team/executives.json
Labels: On Testing

#252 Preload fonts and make the page progressively load faster.
  source/css/elements/_base.scss
  source/layouts/partials/_head.html.erb
Labels: On Testing

#253 Test and fix up the `blog_posts` helper method a bit.
  helpers/middleman/blog.rb
  source/blog/feed.xml.builder
  source/blog/sitemap.xml.erb
  source/sitemap.xml.erb
  spec/features/blog_posts_page_spec.rb
  spec/helpers/blog_helper_spec.rb
  spec/helpers/middleman/blog_spec.rb
  spec/helpers/middleman/space_spec.rb
  spec/models/blog_posts_spec.rb
  spec/support/helpers/blog.rb
Labels: On Testing, Ready to Merge

#254 When getting a Landing Page, use the locale so we get the right title.
  helpers/middleman/landing-pages.rb
  helpers/middleman/locale.rb
  helpers/middleman/page.rb
  source/sitemap.xml.erb
  spec/features/footer_spec.rb
  spec/helpers/middleman/page_spec.rb
Labels: On Testing

#255 Remove the Referrals Program ToCs from the sitemap.
  data/locales.json
Labels: On Testing, Ready to Merge

#256 Use `no_index` instead of `show_in_sitemap` to not index at the page level as well as the sitemap..
  config.rb
  data/locales.json
  source/layouts/partials/_meta.html.erb
  source/robots.txt.erb
  source/sitemap.xml.erb
  spec/features/sitemap_spec.rb
  spec/support/rspec.rb
Labels: On Testing

#248 Redesign Header Navigation
  helpers/middleman/blog.rb
  helpers/middleman/helpers.rb
  helpers/middleman/menu.rb
  helpers/middleman/space.rb
  helpers/middleman/url.rb
  source/css/_config.scss
  source/css/components/_arrow.scss
  source/css/components/_buttons.scss
  source/css/components/_index.scss
  source/css/components/_masthead.scss
  source/css/components/_navigation.scss
  source/css/elements/_accessibility.scss
  source/css/tools/_placeholders.scss
  source/js/localization.js.es6
  source/js/site.js.es6
  source/js/src/hamburger.js
  source/js/src/icons.js.es6
  source/js/src/navigation.js.es6
  source/layouts/layout_index.html.erb
  source/layouts/layout_pro.html.erb
  source/layouts/partials/_body.html.erb
  source/layouts/partials/_head.html.erb
  source/page-survey-thanks.html.erb
  source/partials/_index_hero.html.erb
  source/partials/_main_nav.html.erb
  source/partials/_navigation_in_header.html.erb
  source/partials/_pro_hero.html.erb
  source/partials/_site_footer.html.erb
  source/partials/_site_header.html.erb
  source/partials/_site_header_pro.html.erb
  source/partials/components/_arrow.html.erb
  source/partials/header/_blog.html.erb
  source/partials/header/_caret.html.erb
  source/partials/header/_column.html.erb
  source/partials/header/_desktop_navigation.html.erb
  source/partials/header/_link.html.erb
  source/partials/header/_mobile_navigation.html.erb
  source/partials/header/_navigation.html.erb
  source/partials/header/_row.html.erb
  source/partials/xero_faqs/_how_much_does_cashbook_cost.erb
  source/sections/partials/_button.html.erb
  spec/features/footer_spec.rb
  spec/features/header_spec.rb
  spec/helpers/middleman/blog_spec.rb
  spec/helpers/middleman/menu_spec.rb
  spec/helpers/middleman/url_spec.rb
Labels: On Testing

#257 Try to help the <noscript> from not being read by a screen reader…
  source/layouts/partials/_noscript.html.erb
Labels: On Testing
