Repository sharesight/www.sharesight.com, pull requests merged in 2021-01, with the labels that each got.

#234 Switch Testimonials from ProductReviews to TrustPilot.
  source/css/sections/_product_review.scss
  source/page-index.html.erb
  source/sections/_product_review.html.erb
  source/sections/_trustpilot.html.erb
Labels: On STAGING

#197 Update Ruby from 2.4.2 to 2.6.5
  .github/workflows/bundle-audit.yml
  .github/workflows/main.yml
  .ruby-version
Labels: On STAGING, enhancement

#219 Use `bundler-audit` directly rather than a mis-named package.
  Gemfile
  Gemfile.lock
Labels: On STAGING

#205 Update gems, August 2020
  Gemfile
  Gemfile.lock
Labels: On STAGING, dependencies, ruby

#236 Add "Sharesight Pro" to the footer and overhaul it a bit.
  source/css/components/_footer.scss
  source/partials/_site_footer.html.erb
  spec/features/footer_spec.rb
Labels: On STAGING

#237 Add a "Become a Partner" button onto the Partners Index Page.
  source/css/partners/components/_header.scss
  source/partners/partials/_paginated_header.html.erb
  spec/features/partner_categories_page_spec.rb
  spec/features/partner_featured_page_spec.rb
Labels: On STAGING
