Repository sharesight/www.sharesight.com, pull requests merged in 2021-02, with the labels that each got.

#239 Try limiting `all_entries_page_size` to hopefully paginate data.
  config.rb
Labels: On STAGING

#238 Use the Trustpilot Widget on Xero with a minor refactor to make that sensical.
  source/page-index.html.erb
  source/page-xero.html.erb
  source/sections/_trustpilot.html.erb
Labels: On STAGING, ready to merge

#241 Add tax-deductable blurb to NZ locale
  source/page-pricing.html.erb
Labels: On STAGING, ready for code review
