Repository sharesight/www.sharesight.com, pull requests merged in 2021-05, with the labels that each got.

#271 Adding Multi-Currency Valuation Report to pricing page
  data/plans/global.json
  source/page-pricing.html.erb
Labels: On Testing, Ready for Testing

#272 Use greater/less than equal instead of greater/less than.
  spec/helpers/middleman/blog_spec.rb
Labels: Ready to Merge

#268 Rename [add a redirect for] "Accounting Software" to "Software Providers".
  s3/production-redirection-rules.json
  s3/staging-redirection-rules.json
Labels: On Testing

#281 Minor readme updates
  README.md
Labels: documentation

#279 Styled accordion
  source/css/blog/_page.blog_page.scss
  source/css/blog/_side_nav.scss
  source/css/elements/_accordion.scss
Labels: on staging
