Repository sharesight/www.sharesight.com, pull requests merged in 2021-06, with the labels that each got.

#287 Add url slug and remove Wordpress Url
  helpers/blog_helper.rb
  mappers/blog/post.rb
  migrations/transformWordpressToUrlSlug.js
  spec/helpers/blog_helper_spec.rb
Labels: Ready for Testing, on staging

#286 Video embeds
  source/blog/individual.html.erb
  source/css/elements/_video.scss
  source/js/src/video.js.es6
  source/layouts/partials/_head.html.erb
  source/page-xero.html.erb
  source/partials/video/_explainer.html.erb
  source/partials/video/_tony.html.erb
Labels: on staging

#291 Update user numbers boasts
  helpers/middleman/menu.rb
  source/page-pricing.html.erb
  spec/features/header_spec.rb
Labels: On Testing, Ready to Merge

#292 Have the Pro Navigation `Pricing` link(s) go to an anchor instead.
  helpers/middleman/menu.rb
  mappers/landing-pages/page.rb
  source/page-pro.html.erb
  source/partials/header/_navigation.html.erb
  spec/helpers/middleman/menu_spec.rb
Labels: On Testing

#289 Community forum links and content
  config/environments/development.rb
  config/environments/staging.rb
  data/plans/global.json
  helpers/middleman/menu.rb
  source/partials/_site_footer.html.erb
  spec/features/footer_spec.rb
  spec/features/header_spec.rb
  spec/helpers/middleman/menu_spec.rb
Labels: on staging
