Repository sharesight/www.sharesight.com, pull requests merged in 2021-11, with the labels that each got.

#333 Change 'Your Obligations' to 'Your obligations'
  source/page-sharesight-terms-of-use.html.erb
Labels: Ready to Merge

#337 Remove 404 page!
  data/locales.json
  source/page-404.html.erb
  source/robots.txt.erb
  spec/features/robots_spec.rb
  spec/helpers/middleman/page_spec.rb
Labels: Progress / Don't Merge

#336 Add a link to Gatsby's sitemapindex: `gatsby/sitemap-index.xml`
  source/robots.txt.erb
  spec/features/robots_spec.rb
Labels: on staging

#338 Remove terms of use page
  data/locales.json
  source/page-sharesight-terms-of-use.html.erb
  source/partials/_site_footer.html.erb
Labels: Ready to Merge
