Repository sharesight/www.sharesight.com, pull requests merged in 2022-06, with the labels that each got.

#374 Removing references to blog page
  .github/workflows/main.yml
  config.rb
  config/contentful.rb
  data/locales.json
  extensions/blog.rb
  helpers/blog_helper.rb
  helpers/middleman/blog.rb
  helpers/middleman/helpers.rb
  helpers/middleman/menu.rb
  helpers/middleman/space.rb
  howtos/environment.md
  mappers/blog/post.rb
  source/blog/individual.html.erb
  source/blog/paginated.html.erb
  source/blog/partials/_blog_menu.html.erb
  source/blog/partials/_campaign_monitor.html.erb
  source/blog/partials/_campaign_monitor_sharesight20.html.erb
  source/blog/sharesight20_feed.xml.builder
  source/blog/sitemap.xml.erb
  source/css/_site.scss
  source/css/blog/_buttons.scss
  source/css/blog/_cards.scss
  source/css/blog/_elements.scss
  source/css/blog/_layout.scss
  source/css/blog/_page.blog_page.scss
  source/css/blog/_side_nav.scss
  source/css/blog/_typography.scss
  source/css/components/_navigation.scss
  source/css/sections/_contents.scss
  source/layouts/blog_post.html.erb
  source/partials/header/_blog.html.erb
  source/partners/individual.html.erb
  source/sitemap.xml.erb
  spec/features/blog_categories_page_spec.rb
  spec/features/blog_posts_page_spec.rb
  spec/features/header_spec.rb
  spec/features/sanity_spec.rb
  spec/features/sitemap_spec.rb
  spec/helpers/blog_helper_spec.rb
  spec/helpers/middleman/blog_spec.rb
  spec/helpers/middleman/menu_spec.rb
  spec/helpers/middleman/page_spec.rb
  spec/helpers/middleman/space_spec.rb
  spec/helpers/middleman/url_spec.rb
  spec/models/blog_authors_spec.rb
  spec/models/blog_categories_spec.rb
  spec/models/blog_posts_spec.rb
  spec/models/blog_spec.rb
  spec/support/capybara.rb
  spec/support/helpers/blog.rb
  spec/unit/middleman_helper_spec.rb
Labels: Ready to Merge

#379 Readding card styling back in to fix landing page card styles
  source/css/sections/_contents.scss
Labels: Ready to Merge

#382 Removing references to reviews page
  helpers/middleman/menu.rb
  source/partials/_site_footer.html.erb
  spec/features/external_sanity_spec.rb
Labels: Ready for Testing

#383 Remove Bugsnag
  .github/workflows/main.yml
  config/environments/production.rb
  config/environments/staging.rb
  source/layouts/partials/_analytics_js.html.erb
Labels: on staging
