Repository sharesight/www.sharesight.com, pull requests merged in 2022-01, with the labels that each got.

#346 Remove executive team page
  BEHAVIOUR.md
  data/locales.json
  data/team/executives.json
  helpers/middleman/menu.rb
  source/css/pages/_team.scss
  source/js/localization.js.es6
  source/page-team.html.erb
  source/partials/_site_footer.html.erb
  spec/features/sanity_spec.rb
Labels: on staging

#347 Removing about-sharesight
  data/locales.json
  helpers/middleman/menu.rb
  source/page-about-sharesight.html.erb
  source/page-index.html.erb
  source/partials/_site_footer.html.erb
  spec/helpers/middleman/page_spec.rb
Labels: On Testing

#349 Removing references to investment-portfolio-performance page
  helpers/middleman/menu.rb
Labels: Ready for Code Review, on staging

#348 Removing events page references
  helpers/middleman/menu.rb
  source/partials/_site_footer.html.erb
Labels: Ready for Code Review, on staging

#350 Removing references to FAQ page
  helpers/middleman/menu.rb
  source/partials/_site_footer.html.erb
Labels: Ready for Code Review, on staging

#351 Removing references to affiliates page
  helpers/middleman/menu.rb
  source/partials/_site_footer.html.erb
Labels: Ready for Code Review
