Repository sharesight/www.sharesight.com, pull requests merged in 2022-02, with the labels that each got.

#354 Updating the Sharesight logo
  source/css/components/_navigation.scss
  source/favicon-16x16.png
  source/favicon-32x32.png
  source/favicon.ico
  source/img/logos/logo-neg.svg
  source/img/logos/logo-pro-neg.svg
  source/img/logos/logo-pro.svg
  source/img/logos/logo.svg
  source/layouts/partials/_meta.html.erb
Labels: Ready to Merge, on staging

#362 Fix CVE-2021-30560 by updating Nokogiri version
  Gemfile.lock
Labels: Ready for Code Review

#357 Removing references to investment-portfolio-tax page
  helpers/middleman/menu.rb
Labels: Ready for Testing
